#' Plot left-justified data
#' 
#' @param data Data frame with plot data columns named 'x', 'y', 'y_aboveLOQ', and (if you use version = 2) 'y_LOQ'
#' @param x Name of variable with 'x' data (given as a quoted string); default is 'x'  
#' @param y Name of variable with 'y' data, i.e. uncensored values (given as a quoted string); default is 'y'    
#' @param uncensored Name of variable with data indicating which values are uncensored (1) or censored (0); default is 'uncensored'  
#' @param threshold Name of variable with threshold data for both uncensored and censored data (given as a quoted string); default is 'threshold'  
#' @param results (Optional) Named list of results from lc_linear and/or lc_fixedsplines 
#' @param y_true (Optional) Name of variable with true 'y' data for the model generating the data (if the data has been generated by simulation)      
#' 
#' @import ggplot2
#' 
#' @examples
#' 
#' # 1. Plot data only
#' # Observations from a chemical in cod liver, at one location  
#' data_prepared <- lc_prepare(subset(polybrom, station %in% "23B"), 
#'                             x = "year",
#'                             y = "concentration", 
#'                             censored = "LOQ_flag",
#'                             log = TRUE)
#' lc_plot(data_prepared)
#' 
#' # 2. Plot simulated data  
#' 
#' # Simulate data
#' set.seed(991)
#' X <- seq(from=-1, to=1, by=.025) # generating inputs
#' B <- t(splines::bs(X, knots=seq(-1,1,1), degree=3, intercept = TRUE)) # creating the B-splines
#' num_data <- length(X); num_basis <- nrow(B)
#' a0 <- 0.2 # intercept
#' a <- rnorm(num_basis, 0, 1) # coefficients of B-splines
#' n_param <- length(a)
#' Y_model <- as.vector(a0*X + a%*%B)   # generate expected/mean value  
#' Y <- Y_model + rnorm(length(X),0,.1) # adding noise
#' data_sim <- data.frame(x = X, y_uncensored = Y, y_true = Y_model)
#' # Add censoring 
#' data_sim$y <- data_sim$y_uncensored
#' data_sim$uncensored <- 1
#' threshold_fixed <- -0.3
#' sel <- data_sim$y_uncensored < threshold_fixed
#' data_sim$y[sel] <- NA  
#' data_sim$uncensored[sel] <- 0  
#' data_sim$threshold <- threshold_fixed
#' # Plotting
#' lc_plot(data_sim, y_true = "Y_model")
#' 
#' # 3. Plot with models
#' \dontrun{
#' result_linear <- lc_linear_qi(dat_sim)
#' result_nonlinear <- lc_fixedsplines_qi(dat_sim, knots = 3)
#' lc_plot(dat_sim, 
#'             y_true = "y_true", 
#' results = list(Linear = result_linear,
#'                Nonlinear = result_nonlinear))
#' }
#' 
#' @export
lc_plot <- function(data,
                    x = "x", 
                    y = "y", 
                    uncensored = "uncensored",
                    threshold = "threshold",
                    results = NULL,
                    y_true = NULL){
  data$x <- data[[x]]
  data$y <- data[[y]]
  data$uncensored <- data[[uncensored]]
  data$threshold <- data[[threshold]]
  gg <- ggplot(data, aes(x, y))
  if (!is.null(results)){
    if (is.data.frame(results$plot_data)){
      # If results is not a list of result objects, but just a single result object
      list_name <- deparse(substitute(results)) 
      results <- list(results)
      names(results) <- list_name
      }
    if (is.null(names(results))){
      warning("The list of results should be named. See example 3 in ?lc_plot.")
      names(results) <- paste0("Fit_", 1:length(results))
    }
    for (i in 1:length(results)){
      new_result <- results[[i]]$plot_data
      new_result$Model <- names(results)[i]
      if (i == 1){
        analysis_result <- new_result
      } else {
        analysis_result <- bind_rows(analysis_result, new_result)
      }
    }
    analysis_result$Model <- factor(analysis_result$Model, levels = names(results))
    gg <- gg +
      geom_ribbon(data = analysis_result, aes(ymin = y_lo, ymax = y_hi, fill = Model), alpha = 0.5) +
      geom_line(data = analysis_result, aes(ymin = y_lo, ymax = y_hi, color = Model))
  }
  gg <- gg +
    geom_point() +
    geom_point(data = subset(data, uncensored == 0), aes(y = threshold), shape = 6)
  if (!is.null(y_true)){
    data$y_true <- data[[y_true]]
    gg <- gg +
      geom_line(aes(y = y_true), color = "brown", width = 2)
  }
  gg
}


